---
name: YAML Lint
description: Validate YAML syntax
author: Viktor Varga <viktor@varga.io>

inputs:
  file_or_dir:
    description: File(s) or Directory, separate by space if multiple files or folder are specified
    required: false
  config_file:
    description: Path to custom configuration
    required: false
  config_data:
    description: Custom configuration (as YAML source)
    required: false
  format:
    description: Format for parsing output [parsable,standard,colored,github,auto]
    required: false
    default: github
  strict:
    description: Return non-zero exit code on warnings as well as errors'
    required: false
    default: "false"

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_FILE_OR_DIR: ${{ inputs.file_or_dir }}
    INPUT_CONFIG_FILE: ${{ inputs.config_file }}
    INPUT_CONFIG_DATA: ${{ inputs.config_data }}
    INPUT_FORMAT: ${{ inputs.format }}
    INPUT_STRICT: ${{ inputs.strict }}
